a = 10

try:
    print(a)
except:
    print("a is not exist")
else:
    print("a is Existing")
finally:
    print("The Exception Handling Excecuted")

